import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    // Nav
    dashboard: 'Dashboard',
    customers: 'Customers',
    payments: 'Payments',
    importCSV: 'Import CSV',
    logout: 'Logout',
    // Dashboard
    totalCustomers: 'Total Customers',
    toReceive: 'To Receive',
    todaysIncome: "Today's Income",
    monthlyIncome: 'Monthly Income',
    paid: 'Paid',
    unpaid: 'Unpaid',
    partial: 'Partial',
    activeSubscriptions: 'Active subscriptions',
    needToCollect: 'Need to collect',
    balancePending: 'Balance pending',
    incomeThisMonth: 'Income This Month',
    expiringIn7Days: 'Expiring in 7 days',
    collectionProgress: 'Collection Progress',
    collected: 'collected',
    allGood: 'All good 👍',
    noPayments: 'No payments recorded yet',
    resetDashboard: 'Reset Dashboard',
    resetConfirm: 'This will mark ALL customers as UNPAID and clear all payment history. Are you sure?',
    resetSuccess: 'Dashboard reset successfully',
    // Customers
    addCustomer: 'Add Customer',
    totalRecords: 'total records',
    searchPlaceholder: 'Search by name, CAF number or phone...',
    name: 'Name',
    cafNumber: 'CAF Number',
    phone: 'Phone',
    address: 'Address',
    plan: 'Plan (₹)',
    status: 'Status',
    paidOn: 'Paid On',
    validTill: 'Valid Till',
    balance: 'Balance',
    actions: 'Actions',
    pay: 'Pay',
    noCustomers: 'No customers found',
    // Payment Modal
    paymentType: 'Payment Type',
    fullPaid: 'Full Paid',
    monthsPaid: 'Months Paid',
    amountPaid: 'Amount Paid',
    notes: 'Notes (optional)',
    notesPlaceholder: 'e.g. paid via UPI',
    cancel: 'Cancel',
    confirm: 'Confirm',
    carryOver: 'Carry-over balance from last month',
    carryOverNext: 'Carry-over next month',
    // Import
    importCustomers: 'Import Customers',
    uploadSubtitle: 'Upload APSFL export — CSV, Excel, or TXT',
    expectedColumns: 'Expected Columns',
    dropFile: 'Drop file here or click to browse',
    importing: 'Importing...',
    importBtn: '⬆️  Import Customers',
    importResult: 'Import Result',
    totalRows: 'Total Rows',
    imported: 'Imported',
    skipped: 'Skipped',
    howToExport: 'How to export from APSFL',
    // Payments
    paymentHistory: 'Payment History',
    type: 'Type',
    amount: 'Amount',
    months: 'Months',
    customer: 'Customer',
    from: 'From',
    to: 'To',
    filter: 'Filter',
    clear: 'Clear',
    total: 'Total',
    noPaymentRecords: 'No payment records found',
    // Add Customer
    customerName: 'Customer Name *',
    cafNumberLabel: 'CAF Number *',
    phoneNumber: 'Phone Number',
    monthlyPlan: 'Monthly Plan Amount (₹)',
    notesLabel: 'Notes',
    adding: 'Adding...',
    addBtn: 'Add Customer',
    paidThisMonth: '% paid this month',
    closeBtn: 'Close',
    paymentHistoryFor: 'Payment History for',
    noHistoryFound: 'No history found for this customer.',
  },
  te: {
    // Nav
    dashboard: 'డాష్‌బోర్డ్',
    customers: 'కస్టమర్లు',
    payments: 'చెల్లింపులు',
    importCSV: 'దిగుమతి CSV',
    logout: 'లాగ్అవుట్',
    // Dashboard
    totalCustomers: 'మొత్తం కస్టమర్లు',
    toReceive: 'అందుకోవాల్సింది',
    todaysIncome: 'నేటి ఆదాయం',
    monthlyIncome: 'నెలవారీ ఆదాయం',
    paid: 'చెల్లించారు',
    unpaid: 'చెల్లించలేదు',
    partial: 'పాక్షికం',
    activeSubscriptions: 'క్రియాశీల సభ్యత్వాలు',
    needToCollect: 'వసూలు చేయాలి',
    balancePending: 'బకాయి పెండింగ్',
    incomeThisMonth: 'ఈ నెల ఆదాయం',
    expiringIn7Days: '7 రోజుల్లో గడువు',
    collectionProgress: 'వసూలు పురోగతి',
    collected: 'వసూలైంది',
    allGood: 'అంతా సరిగ్గా ఉంది 👍',
    noPayments: 'ఇంకా చెల్లింపులు నమోదు కాలేదు',
    resetDashboard: 'డాష్‌బోర్డ్ రీసెట్',
    resetConfirm: 'ఇది అన్ని కస్టమర్లను UNPAID గా మార్చి చెల్లింపు చరిత్రను తొలగిస్తుంది. మీరు ఖచ్చితంగా ఉన్నారా?',
    resetSuccess: 'డాష్‌బోర్డ్ విజయవంతంగా రీసెట్ అయింది',
    // Customers
    addCustomer: 'కస్టమర్ జోడించు',
    totalRecords: 'మొత్తం రికార్డులు',
    searchPlaceholder: 'పేరు, CAF నంబర్ లేదా ఫోన్ ద్వారా వెతకండి...',
    name: 'పేరు',
    cafNumber: 'CAF నంబర్',
    phone: 'ఫోన్',
    address: 'చిరునామా',
    plan: 'ప్లాన్ (₹)',
    status: 'స్థితి',
    paidOn: 'చెల్లించిన తేదీ',
    validTill: 'చెల్లుబాటు వరకు',
    balance: 'బకాయి',
    actions: 'చర్యలు',
    pay: 'చెల్లింపు',
    noCustomers: 'కస్టమర్లు కనుగొనబడలేదు',
    // Payment Modal
    paymentType: 'చెల్లింపు రకం',
    fullPaid: 'పూర్తిగా చెల్లించారు',
    monthsPaid: 'నెలలు చెల్లించారు',
    amountPaid: 'చెల్లించిన మొత్తం',
    notes: 'గమనికలు (ఐచ్ఛికం)',
    notesPlaceholder: 'ఉదా. UPI ద్వారా చెల్లించారు',
    cancel: 'రద్దు',
    confirm: 'నిర్ధారించు',
    carryOver: 'గత నెల నుండి బకాయి',
    carryOverNext: 'వచ్చే నెల బకాయి',
    // Import
    importCustomers: 'కస్టమర్లను దిగుమతి చేయండి',
    uploadSubtitle: 'APSFL ఎగుమతి అప్‌లోడ్ చేయండి — CSV, Excel, లేదా TXT',
    expectedColumns: 'అవసరమైన కాలమ్‌లు',
    dropFile: 'ఫైల్‌ను ఇక్కడ వదలండి లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి',
    importing: 'దిగుమతి అవుతోంది...',
    importBtn: '⬆️  కస్టమర్లను దిగుమతి చేయండి',
    importResult: 'దిగుమతి ఫలితం',
    totalRows: 'మొత్తం వరుసలు',
    imported: 'దిగుమతి అయ్యాయి',
    skipped: 'దాటవేయబడ్డాయి',
    howToExport: 'APSFL నుండి ఎలా ఎగుమతి చేయాలి',
    // Payments
    paymentHistory: 'చెల్లింపు చరిత్ర',
    type: 'రకం',
    amount: 'మొత్తం',
    months: 'నెలలు',
    customer: 'కస్టమర్',
    from: 'నుండి',
    to: 'వరకు',
    filter: 'వడపోత',
    clear: 'తుడవండి',
    total: 'మొత్తం',
    noPaymentRecords: 'చెల్లింపు రికార్డులు కనుగొనబడలేదు',
    // Add Customer
    customerName: 'కస్టమర్ పేరు *',
    cafNumberLabel: 'CAF నంబర్ *',
    phoneNumber: 'ఫోన్ నంబర్',
    monthlyPlan: 'నెలవారీ ప్లాన్ మొత్తం (₹)',
    notesLabel: 'గమనికలు',
    adding: 'జోడిస్తోంది...',
    addBtn: 'కస్టమర్ జోడించు',
    paidThisMonth: '% ఈ నెల చెల్లించారు',
    closeBtn: 'మూసివేయు',
    paymentHistoryFor: 'చెల్లింపు చరిత్ర -',
    noHistoryFound: 'ఈ కస్టమర్‌కు చరిత్ర లేదు.',
  }
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = (key) => translations[lang][key] || translations['en'][key] || key
  const toggleLang = () => setLang(l => l === 'en' ? 'te' : 'en')
  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLang = () => useContext(LanguageContext)
